### ISSUE TITLE
Gaussian mixture KL derivation

### ISSUE THREAD

**Issue by emilemathieu** [RuiShu/vae-experiments#2]
Hi! Thanks a lot for this repo :)

I was wondering how did you come up with line (20) in `gmm_kld_derivation.pdf`. Is it a lower bound or some kind ?

Cheers,
Emile

**Comment by RuiShu** [comment]
I got it from https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=4218101 c:

In retrospect, I would have implemented this very differently.

**Comment by emilemathieu** [comment]
Cheers !
What would you change ?

**Comment by RuiShu** [comment]
I would've just approximated KL via monte carlo estimation. The estimator will be unbiased (albeit with higher variance) and the higher variance doesn't really seem to hurt VAE performance in practice.

**Comment by emilemathieu** [comment]
Indeed, and one could control that variance by increasing the number of samples. How one would choose that number ?

**Comment by RuiShu** [comment]
My default choice would be 1 Monte Carlo sample.
